name: reusable-gke-deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      deployment_tag:
        required: true
        type: string
      container_registry_name:
        required: false
        type: string
        default: ghcr.io
      workload_identity_provider:
        required: true
        type: string
      gke_service_account:
        required: true
        type: string
      gke_cluster:
        required: true
        type: string
      gke_region:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.gke_service_account }}

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ${{ inputs.gke_cluster }}
          location: ${{ inputs.gke_region }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Deploy k8s objects to the GKE cluster
      - name: Deploy to GKE
        run: |-
          export IMAGE_NAME=${{ inputs.container_registry_name }}/${{ inputs.image_name }}:${{ inputs.deployment_tag }}
          echo $IMAGE_NAME
          sed -Ei "s|IMAGE_PLACEHOLDER|$IMAGE_NAME|g" k8s/deployment.yaml
          kubectl apply -f k8s/
